### ISSUE TITLE
Толщина шрифта в slide-title

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#11]
По макету там не old

![2015-09-23 10-20-55 n rd s](https://cloud.githubusercontent.com/assets/223620/10039655/ece4e136-61dc-11e5-92ef-a0fae90ff5ec.png)
![screen shot 2015-09-23 at 10 16 28](https://cloud.githubusercontent.com/assets/223620/10039654/ece15ac0-61dc-11e5-9861-1b292b6e886e.png)

**Comment by cantcool** [comment]
Копировал стили из их "Демонстрации" и не заметил.
Fixed https://github.com/cantcool/id80994_nerds/commit/dfd4aa255fef9af8a36e3ed79e617cb390ba210f

**Comment by alexbaumgertner** [comment]
Да, я для себя установил мантру: "при копипасте проверяй трижды, особенно когда копипастишь сам  себя" :)
