### ISSUE TITLE
Размер шрифта для фото товаров

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#12]
![2015-09-23 10-26-45 n rd s](https://cloud.githubusercontent.com/assets/223620/10039753/de489dce-61dd-11e5-9864-81081f1a69f7.png)
Из-за обнуления шрифта для https://github.com/cantcool/id80994_nerds/blob/master/css/style.css#L774
`alt` у фото `.shop-item img` не показывается. Можно добавить font-size 14 px

**Comment by cantcool** [comment]
Added https://github.com/cantcool/id80994_nerds/commit/eaa19cd271a5b5c8535c68d0da7b793c08178108
