### ISSUE TITLE
Убрать float у shop-string-filter-right

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#13]
Из-за этого float разваливается блок (yandex browser)
![2015-09-23 10-31-12 n rd s](https://cloud.githubusercontent.com/assets/223620/10039808/4ce43824-61de-11e5-9b7e-6fa279c02dae.png)

Можно его убрать:

![2015-09-23 10-30-56 n rd s](https://cloud.githubusercontent.com/assets/223620/10039807/4cb53f10-61de-11e5-9c2e-384204b97bf9.png)

**Comment by cantcool** [comment]
Fixed https://github.com/cantcool/id80994_nerds/commit/2ad14a7becff8c1274ba4b4c4b28d13863759b68
