### ISSUE TITLE
Толщина заголовков

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#4]
В макете заголовки
* `.index-content h2`
* `.footer-text h3`

нормальной толщины. Нужно указать `font-weight: normal;` для них, так как по умолчанию для всех элементов  `h1-h6` значение толщины `font-weight: bold;`

**Comment by cantcool** [comment]
Насколько я понимаю, font-weight: **normal**  — это **400**. А у нас везде Roboto **Medium**. Поэтому я задал заголовкам font-weight: **500**
https://github.com/cantcool/id80994_nerds/commit/b9d1e4983c4325c101297c99acd83c7d46a5fde7

**Comment by alexbaumgertner** [comment]
:ok:
