### ISSUE TITLE
Поправить расположение блока map-address

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#5]
Сейчас блок `map-address` располагается левее, чем в макете:
![2015-09-20 07-52-49 n rd s](https://cloud.githubusercontent.com/assets/223620/9979270/c3d5dec0-5f6c-11e5-8cb4-3462b682d9a6.png)
Должен быть выровнен по иконкам соц сетей.

**Comment by cantcool** [comment]
Fixed https://github.com/cantcool/id80994_nerds/commit/2d3be5a946feed36f42739c0a2ad6d672b588ea6

**Comment by alexbaumgertner** [comment]
:ok>
