### ISSUE TITLE
Указать отступ для текста в блоке .contact-form textarea

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#6]
В поле ввода ` .contact-form textarea` не правильный отступ введенного текста:
![2015-09-20 08-04-01 n rd s](https://cloud.githubusercontent.com/assets/223620/9979308/c4f53cae-5f6e-11e5-9881-1f094bac8479.png)

По умолчанию у HTML-элементов `textarea` задается `padding`, он не всегда соответствует макету. Нужно задать его вручную.

**Comment by cantcool** [comment]
Поправил, стало так: http://i.imgur.com/CmVwr3F.png
https://github.com/cantcool/id80994_nerds/commit/9a4d93e9ba046dfeba2b488e94d339c7dd44c118

**Comment by alexbaumgertner** [comment]
:ok:
