### ISSUE TITLE
Добавить курсор pointer для контролов форм

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#7]
![2015-09-20 22-21-57 current call](https://cloud.githubusercontent.com/assets/223620/9982456/1a8a8512-5fe6-11e5-9ba6-aac1203969db.png)

**Comment by cantcool** [comment]
Done, https://github.com/cantcool/id80994_nerds/commit/e7ef3eb881ec57b219daeb74c564edae5b75364a
