### ISSUE TITLE
К странице каталога не подключен normalize.css

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#8]
В index есть https://github.com/cantcool/id80994_nerds/blob/master/index.html#L6-L7
в catalog нет https://github.com/cantcool/id80994_nerds/blob/master/catalog.html#L6

**Comment by cantcool** [comment]
Fixed, https://github.com/cantcool/id80994_nerds/commit/04a39972a29fff04a56cf3822570d1f440eff95e

**Comment by alexbaumgertner** [comment]
:+1:
